"""Initial schema with all models

Revision ID: 9260c9e2a970
Revises: 
Create Date: 2025-12-21 19:16:55.859619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9260c9e2a970'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sector_identifier_enabled', sa.Boolean(), nullable=False),
    sa.Column('liquidity_hunter_enabled', sa.Boolean(), nullable=False),
    sa.Column('market_depth_enabled', sa.Boolean(), nullable=False),
    sa.Column('floorsheet_enabled', sa.Boolean(), nullable=False),
    sa.Column('fundamental_enabled', sa.Boolean(), nullable=False),
    sa.Column('sector_comparison_days', sa.Integer(), nullable=False),
    sa.Column('sector_momentum_threshold', sa.Float(), nullable=False),
    sa.Column('min_beta', sa.Float(), nullable=False),
    sa.Column('max_beta', sa.Float(), nullable=False),
    sa.Column('volume_days', sa.Integer(), nullable=False),
    sa.Column('volume_threshold', sa.Float(), nullable=False),
    sa.Column('min_volatility', sa.Float(), nullable=False),
    sa.Column('max_volatility', sa.Float(), nullable=False),
    sa.Column('demand_zone_lookback', sa.Integer(), nullable=False),
    sa.Column('volume_spike_threshold', sa.Float(), nullable=False),
    sa.Column('rsi_oversold', sa.Float(), nullable=False),
    sa.Column('rsi_overbought', sa.Float(), nullable=False),
    sa.Column('support_resistance_strength', sa.Integer(), nullable=False),
    sa.Column('breakout_volume_threshold', sa.Float(), nullable=False),
    sa.Column('pattern_lookback_days', sa.Integer(), nullable=False),
    sa.Column('order_imbalance_threshold', sa.Float(), nullable=False),
    sa.Column('bid_wall_threshold', sa.Float(), nullable=False),
    sa.Column('liquidity_score_threshold', sa.Float(), nullable=False),
    sa.Column('broker_accumulation_days', sa.Integer(), nullable=False),
    sa.Column('broker_volume_threshold', sa.Float(), nullable=False),
    sa.Column('manipulation_detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_per_trade', sa.Float(), nullable=False),
    sa.Column('max_risk_per_trade', sa.Float(), nullable=False),
    sa.Column('reward_risk_ratio', sa.Float(), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('ema_short_period', sa.Integer(), nullable=False),
    sa.Column('ema_long_period', sa.Integer(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=False),
    sa.Column('macd_fast', sa.Integer(), nullable=False),
    sa.Column('macd_slow', sa.Integer(), nullable=False),
    sa.Column('macd_signal', sa.Integer(), nullable=False),
    sa.Column('bollinger_period', sa.Integer(), nullable=False),
    sa.Column('bollinger_std', sa.Float(), nullable=False),
    sa.Column('atr_period', sa.Integer(), nullable=False),
    sa.Column('min_confidence_score', sa.Float(), nullable=False),
    sa.Column('component_weights', sa.JSON(), nullable=True),
    sa.Column('market_data_interval', sa.Integer(), nullable=False),
    sa.Column('analysis_interval', sa.Integer(), nullable=False),
    sa.Column('signal_generation_interval', sa.Integer(), nullable=False),
    sa.Column('additional_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configurations_id'), 'bot_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_bot_configurations_is_active'), 'bot_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_bot_configurations_name'), 'bot_configurations', ['name'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('current_index', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('day_high', sa.Float(), nullable=True),
    sa.Column('day_low', sa.Float(), nullable=True),
    sa.Column('week_high', sa.Float(), nullable=True),
    sa.Column('week_low', sa.Float(), nullable=True),
    sa.Column('month_high', sa.Float(), nullable=True),
    sa.Column('month_low', sa.Float(), nullable=True),
    sa.Column('year_high', sa.Float(), nullable=True),
    sa.Column('year_low', sa.Float(), nullable=True),
    sa.Column('momentum_1d', sa.Float(), nullable=True),
    sa.Column('momentum_5d', sa.Float(), nullable=True),
    sa.Column('momentum_10d', sa.Float(), nullable=True),
    sa.Column('momentum_20d', sa.Float(), nullable=True),
    sa.Column('momentum_30d', sa.Float(), nullable=True),
    sa.Column('relative_strength_1d', sa.Float(), nullable=True),
    sa.Column('relative_strength_5d', sa.Float(), nullable=True),
    sa.Column('relative_strength_10d', sa.Float(), nullable=True),
    sa.Column('relative_strength_20d', sa.Float(), nullable=True),
    sa.Column('relative_strength_30d', sa.Float(), nullable=True),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('total_turnover', sa.Float(), nullable=True),
    sa.Column('avg_volume_10d', sa.Float(), nullable=True),
    sa.Column('avg_volume_30d', sa.Float(), nullable=True),
    sa.Column('total_stocks', sa.Integer(), nullable=True),
    sa.Column('advancing_stocks', sa.Integer(), nullable=True),
    sa.Column('declining_stocks', sa.Integer(), nullable=True),
    sa.Column('unchanged_stocks', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_code', 'sectors', ['code'], unique=False)
    op.create_index('idx_sector_momentum', 'sectors', ['momentum_30d'], unique=False)
    op.create_index('idx_sector_name', 'sectors', ['name'], unique=False)
    op.create_index('idx_sector_rank', 'sectors', ['rank'], unique=False)
    op.create_index('idx_sector_updated', 'sectors', ['last_updated'], unique=False)
    op.create_index(op.f('ix_sectors_code'), 'sectors', ['code'], unique=True)
    op.create_index(op.f('ix_sectors_id'), 'sectors', ['id'], unique=False)
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_tradeable', sa.Boolean(), nullable=False),
    sa.Column('listing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('week_52_high', sa.Float(), nullable=True),
    sa.Column('week_52_low', sa.Float(), nullable=True),
    sa.Column('week_52_high_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('week_52_low_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('outstanding_shares', sa.Float(), nullable=True),
    sa.Column('free_float', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('book_value', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('avg_volume_10d', sa.Float(), nullable=True),
    sa.Column('avg_volume_30d', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_9', sa.Float(), nullable=True),
    sa.Column('ema_21', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('support_1', sa.Float(), nullable=True),
    sa.Column('support_2', sa.Float(), nullable=True),
    sa.Column('support_3', sa.Float(), nullable=True),
    sa.Column('resistance_1', sa.Float(), nullable=True),
    sa.Column('resistance_2', sa.Float(), nullable=True),
    sa.Column('resistance_3', sa.Float(), nullable=True),
    sa.Column('passes_volume_filter', sa.Boolean(), nullable=False),
    sa.Column('passes_beta_filter', sa.Boolean(), nullable=False),
    sa.Column('passes_volatility_filter', sa.Boolean(), nullable=False),
    sa.Column('in_bullish_sector', sa.Boolean(), nullable=False),
    sa.Column('last_traded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indicators_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_active', 'stocks', ['is_active'], unique=False)
    op.create_index('idx_stock_beta', 'stocks', ['beta'], unique=False)
    op.create_index('idx_stock_filters', 'stocks', ['passes_volume_filter', 'passes_beta_filter', 'passes_volatility_filter'], unique=False)
    op.create_index('idx_stock_sector', 'stocks', ['sector_id'], unique=False)
    op.create_index('idx_stock_symbol', 'stocks', ['symbol'], unique=False)
    op.create_index('idx_stock_tradeable', 'stocks', ['is_tradeable'], unique=False)
    op.create_index('idx_stock_updated', 'stocks', ['updated_at'], unique=False)
    op.create_index('idx_stock_volume', 'stocks', ['avg_volume_30d'], unique=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_is_active'), 'stocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_sector_id'), 'stocks', ['sector_id'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('floorsheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trade_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contract_id', sa.String(length=50), nullable=True),
    sa.Column('buyer_broker_id', sa.String(length=20), nullable=False),
    sa.Column('buyer_broker_name', sa.String(length=200), nullable=True),
    sa.Column('seller_broker_id', sa.String(length=20), nullable=False),
    sa.Column('seller_broker_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_institutional', sa.Integer(), nullable=False),
    sa.Column('is_cross_trade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_floorsheet_amount', 'floorsheet', ['amount'], unique=False)
    op.create_index('idx_floorsheet_brokers', 'floorsheet', ['buyer_broker_id', 'seller_broker_id'], unique=False)
    op.create_index('idx_floorsheet_buyer_broker', 'floorsheet', ['buyer_broker_id'], unique=False)
    op.create_index('idx_floorsheet_institutional', 'floorsheet', ['is_institutional'], unique=False)
    op.create_index('idx_floorsheet_seller_broker', 'floorsheet', ['seller_broker_id'], unique=False)
    op.create_index('idx_floorsheet_stock_date', 'floorsheet', ['stock_id', 'trade_date'], unique=False)
    op.create_index('idx_floorsheet_stock_id', 'floorsheet', ['stock_id'], unique=False)
    op.create_index('idx_floorsheet_trade_date', 'floorsheet', ['trade_date'], unique=False)
    op.create_index(op.f('ix_floorsheet_buyer_broker_id'), 'floorsheet', ['buyer_broker_id'], unique=False)
    op.create_index(op.f('ix_floorsheet_contract_id'), 'floorsheet', ['contract_id'], unique=True)
    op.create_index(op.f('ix_floorsheet_id'), 'floorsheet', ['id'], unique=False)
    op.create_index(op.f('ix_floorsheet_seller_broker_id'), 'floorsheet', ['seller_broker_id'], unique=False)
    op.create_index(op.f('ix_floorsheet_stock_id'), 'floorsheet', ['stock_id'], unique=False)
    op.create_index(op.f('ix_floorsheet_trade_date'), 'floorsheet', ['trade_date'], unique=False)
    op.create_table('market_depth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('buy_price_1', sa.Float(), nullable=True),
    sa.Column('buy_quantity_1', sa.Float(), nullable=True),
    sa.Column('buy_orders_1', sa.Integer(), nullable=True),
    sa.Column('buy_price_2', sa.Float(), nullable=True),
    sa.Column('buy_quantity_2', sa.Float(), nullable=True),
    sa.Column('buy_orders_2', sa.Integer(), nullable=True),
    sa.Column('buy_price_3', sa.Float(), nullable=True),
    sa.Column('buy_quantity_3', sa.Float(), nullable=True),
    sa.Column('buy_orders_3', sa.Integer(), nullable=True),
    sa.Column('buy_price_4', sa.Float(), nullable=True),
    sa.Column('buy_quantity_4', sa.Float(), nullable=True),
    sa.Column('buy_orders_4', sa.Integer(), nullable=True),
    sa.Column('buy_price_5', sa.Float(), nullable=True),
    sa.Column('buy_quantity_5', sa.Float(), nullable=True),
    sa.Column('buy_orders_5', sa.Integer(), nullable=True),
    sa.Column('sell_price_1', sa.Float(), nullable=True),
    sa.Column('sell_quantity_1', sa.Float(), nullable=True),
    sa.Column('sell_orders_1', sa.Integer(), nullable=True),
    sa.Column('sell_price_2', sa.Float(), nullable=True),
    sa.Column('sell_quantity_2', sa.Float(), nullable=True),
    sa.Column('sell_orders_2', sa.Integer(), nullable=True),
    sa.Column('sell_price_3', sa.Float(), nullable=True),
    sa.Column('sell_quantity_3', sa.Float(), nullable=True),
    sa.Column('sell_orders_3', sa.Integer(), nullable=True),
    sa.Column('sell_price_4', sa.Float(), nullable=True),
    sa.Column('sell_quantity_4', sa.Float(), nullable=True),
    sa.Column('sell_orders_4', sa.Integer(), nullable=True),
    sa.Column('sell_price_5', sa.Float(), nullable=True),
    sa.Column('sell_quantity_5', sa.Float(), nullable=True),
    sa.Column('sell_orders_5', sa.Integer(), nullable=True),
    sa.Column('total_buy_quantity', sa.Float(), nullable=True),
    sa.Column('total_sell_quantity', sa.Float(), nullable=True),
    sa.Column('total_buy_orders', sa.Integer(), nullable=True),
    sa.Column('total_sell_orders', sa.Integer(), nullable=True),
    sa.Column('order_imbalance', sa.Float(), nullable=True),
    sa.Column('bid_ask_spread', sa.Float(), nullable=True),
    sa.Column('bid_ask_spread_percent', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('depth_ratio', sa.Float(), nullable=True),
    sa.Column('has_bid_wall', sa.Integer(), nullable=False),
    sa.Column('has_ask_wall', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_depth_imbalance', 'market_depth', ['order_imbalance'], unique=False)
    op.create_index('idx_market_depth_stock_id', 'market_depth', ['stock_id'], unique=False)
    op.create_index('idx_market_depth_stock_timestamp', 'market_depth', ['stock_id', 'timestamp'], unique=False)
    op.create_index('idx_market_depth_timestamp', 'market_depth', ['timestamp'], unique=False)
    op.create_index('idx_market_depth_walls', 'market_depth', ['has_bid_wall', 'has_ask_wall'], unique=False)
    op.create_index(op.f('ix_market_depth_id'), 'market_depth', ['id'], unique=False)
    op.create_index(op.f('ix_market_depth_stock_id'), 'market_depth', ['stock_id'], unique=False)
    op.create_index(op.f('ix_market_depth_timestamp'), 'market_depth', ['timestamp'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pattern_type', sa.Enum('SUPPORT', 'RESISTANCE', 'TREND_LINE', 'DOUBLE_TOP', 'DOUBLE_BOTTOM', 'HEAD_SHOULDERS', 'INVERSE_HEAD_SHOULDERS', 'TRIANGLE_ASCENDING', 'TRIANGLE_DESCENDING', 'TRIANGLE_SYMMETRICAL', 'FLAG_BULLISH', 'FLAG_BEARISH', 'PENNANT', 'WEDGE_RISING', 'WEDGE_FALLING', 'CHANNEL_ASCENDING', 'CHANNEL_DESCENDING', 'BREAKOUT_BULLISH', 'BREAKOUT_BEARISH', name='patterntype'), nullable=False),
    sa.Column('status', sa.Enum('FORMING', 'CONFIRMED', 'BROKEN', 'COMPLETED', name='patternstatus'), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('level_1', sa.Float(), nullable=True),
    sa.Column('level_2', sa.Float(), nullable=True),
    sa.Column('level_3', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('touches', sa.Integer(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('breakout_price', sa.Float(), nullable=True),
    sa.Column('breakout_date', sa.Date(), nullable=True),
    sa.Column('breakout_volume', sa.Float(), nullable=True),
    sa.Column('volume_confirmation', sa.Integer(), nullable=False),
    sa.Column('target_1', sa.Float(), nullable=True),
    sa.Column('target_2', sa.Float(), nullable=True),
    sa.Column('target_3', sa.Float(), nullable=True),
    sa.Column('invalidation_level', sa.Float(), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('first_detected', sa.Date(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_active', 'patterns', ['status', 'first_detected'], unique=False)
    op.create_index('idx_pattern_detected', 'patterns', ['first_detected'], unique=False)
    op.create_index('idx_pattern_status', 'patterns', ['status'], unique=False)
    op.create_index('idx_pattern_stock_id', 'patterns', ['stock_id'], unique=False)
    op.create_index('idx_pattern_stock_type', 'patterns', ['stock_id', 'pattern_type'], unique=False)
    op.create_index('idx_pattern_type', 'patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_patterns_first_detected'), 'patterns', ['first_detected'], unique=False)
    op.create_index(op.f('ix_patterns_id'), 'patterns', ['id'], unique=False)
    op.create_index(op.f('ix_patterns_pattern_type'), 'patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_patterns_status'), 'patterns', ['status'], unique=False)
    op.create_index(op.f('ix_patterns_stock_id'), 'patterns', ['stock_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('bot_config_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', name='signaltype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXECUTED', 'CANCELLED', 'EXPIRED', name='signalstatus'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('take_profit_3', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('sector_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('depth_score', sa.Float(), nullable=True),
    sa.Column('floorsheet_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('sector_bullish', sa.Integer(), nullable=False),
    sa.Column('in_demand_zone', sa.Integer(), nullable=False),
    sa.Column('has_volume_spike', sa.Integer(), nullable=False),
    sa.Column('has_breakout', sa.Integer(), nullable=False),
    sa.Column('has_bid_wall', sa.Integer(), nullable=False),
    sa.Column('has_accumulation', sa.Integer(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('ema_9', sa.Float(), nullable=True),
    sa.Column('ema_21', sa.Float(), nullable=True),
    sa.Column('detected_patterns', sa.JSON(), nullable=True),
    sa.Column('signal_reason', sa.String(length=500), nullable=True),
    sa.Column('component_details', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_percent', sa.Float(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configurations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_active', 'signals', ['status', 'valid_until'], unique=False)
    op.create_index('idx_signal_confidence', 'signals', ['confidence_score'], unique=False)
    op.create_index('idx_signal_generated', 'signals', ['generated_at'], unique=False)
    op.create_index('idx_signal_status', 'signals', ['status'], unique=False)
    op.create_index('idx_signal_stock_id', 'signals', ['stock_id'], unique=False)
    op.create_index('idx_signal_stock_status', 'signals', ['stock_id', 'status'], unique=False)
    op.create_index('idx_signal_type', 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_bot_config_id'), 'signals', ['bot_config_id'], unique=False)
    op.create_index(op.f('ix_signals_confidence_score'), 'signals', ['confidence_score'], unique=False)
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_stock_id'), 'signals', ['stock_id'], unique=False)
    op.create_table('stock_ohlcv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('body_size', sa.Float(), nullable=True),
    sa.Column('upper_shadow', sa.Float(), nullable=True),
    sa.Column('lower_shadow', sa.Float(), nullable=True),
    sa.Column('candle_range', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', name='uq_stock_date')
    )
    op.create_index('idx_ohlcv_date', 'stock_ohlcv', ['date'], unique=False)
    op.create_index('idx_ohlcv_stock_date', 'stock_ohlcv', ['stock_id', 'date'], unique=False)
    op.create_index('idx_ohlcv_stock_id', 'stock_ohlcv', ['stock_id'], unique=False)
    op.create_index('idx_ohlcv_volume', 'stock_ohlcv', ['volume'], unique=False)
    op.create_index(op.f('ix_stock_ohlcv_date'), 'stock_ohlcv', ['date'], unique=False)
    op.create_index(op.f('ix_stock_ohlcv_id'), 'stock_ohlcv', ['id'], unique=False)
    op.create_index(op.f('ix_stock_ohlcv_stock_id'), 'stock_ohlcv', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ohlcv_stock_id'), table_name='stock_ohlcv')
    op.drop_index(op.f('ix_stock_ohlcv_id'), table_name='stock_ohlcv')
    op.drop_index(op.f('ix_stock_ohlcv_date'), table_name='stock_ohlcv')
    op.drop_index('idx_ohlcv_volume', table_name='stock_ohlcv')
    op.drop_index('idx_ohlcv_stock_id', table_name='stock_ohlcv')
    op.drop_index('idx_ohlcv_stock_date', table_name='stock_ohlcv')
    op.drop_index('idx_ohlcv_date', table_name='stock_ohlcv')
    op.drop_table('stock_ohlcv')
    op.drop_index(op.f('ix_signals_stock_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_confidence_score'), table_name='signals')
    op.drop_index(op.f('ix_signals_bot_config_id'), table_name='signals')
    op.drop_index('idx_signal_type', table_name='signals')
    op.drop_index('idx_signal_stock_status', table_name='signals')
    op.drop_index('idx_signal_stock_id', table_name='signals')
    op.drop_index('idx_signal_status', table_name='signals')
    op.drop_index('idx_signal_generated', table_name='signals')
    op.drop_index('idx_signal_confidence', table_name='signals')
    op.drop_index('idx_signal_active', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_patterns_stock_id'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_status'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_pattern_type'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_id'), table_name='patterns')
    op.drop_index(op.f('ix_patterns_first_detected'), table_name='patterns')
    op.drop_index('idx_pattern_type', table_name='patterns')
    op.drop_index('idx_pattern_stock_type', table_name='patterns')
    op.drop_index('idx_pattern_stock_id', table_name='patterns')
    op.drop_index('idx_pattern_status', table_name='patterns')
    op.drop_index('idx_pattern_detected', table_name='patterns')
    op.drop_index('idx_pattern_active', table_name='patterns')
    op.drop_table('patterns')
    op.drop_index(op.f('ix_market_depth_timestamp'), table_name='market_depth')
    op.drop_index(op.f('ix_market_depth_stock_id'), table_name='market_depth')
    op.drop_index(op.f('ix_market_depth_id'), table_name='market_depth')
    op.drop_index('idx_market_depth_walls', table_name='market_depth')
    op.drop_index('idx_market_depth_timestamp', table_name='market_depth')
    op.drop_index('idx_market_depth_stock_timestamp', table_name='market_depth')
    op.drop_index('idx_market_depth_stock_id', table_name='market_depth')
    op.drop_index('idx_market_depth_imbalance', table_name='market_depth')
    op.drop_table('market_depth')
    op.drop_index(op.f('ix_floorsheet_trade_date'), table_name='floorsheet')
    op.drop_index(op.f('ix_floorsheet_stock_id'), table_name='floorsheet')
    op.drop_index(op.f('ix_floorsheet_seller_broker_id'), table_name='floorsheet')
    op.drop_index(op.f('ix_floorsheet_id'), table_name='floorsheet')
    op.drop_index(op.f('ix_floorsheet_contract_id'), table_name='floorsheet')
    op.drop_index(op.f('ix_floorsheet_buyer_broker_id'), table_name='floorsheet')
    op.drop_index('idx_floorsheet_trade_date', table_name='floorsheet')
    op.drop_index('idx_floorsheet_stock_id', table_name='floorsheet')
    op.drop_index('idx_floorsheet_stock_date', table_name='floorsheet')
    op.drop_index('idx_floorsheet_seller_broker', table_name='floorsheet')
    op.drop_index('idx_floorsheet_institutional', table_name='floorsheet')
    op.drop_index('idx_floorsheet_buyer_broker', table_name='floorsheet')
    op.drop_index('idx_floorsheet_brokers', table_name='floorsheet')
    op.drop_index('idx_floorsheet_amount', table_name='floorsheet')
    op.drop_table('floorsheet')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_is_active'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_index('idx_stock_volume', table_name='stocks')
    op.drop_index('idx_stock_updated', table_name='stocks')
    op.drop_index('idx_stock_tradeable', table_name='stocks')
    op.drop_index('idx_stock_symbol', table_name='stocks')
    op.drop_index('idx_stock_sector', table_name='stocks')
    op.drop_index('idx_stock_filters', table_name='stocks')
    op.drop_index('idx_stock_beta', table_name='stocks')
    op.drop_index('idx_stock_active', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_id'), table_name='sectors')
    op.drop_index(op.f('ix_sectors_code'), table_name='sectors')
    op.drop_index('idx_sector_updated', table_name='sectors')
    op.drop_index('idx_sector_rank', table_name='sectors')
    op.drop_index('idx_sector_name', table_name='sectors')
    op.drop_index('idx_sector_momentum', table_name='sectors')
    op.drop_index('idx_sector_code', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_bot_configurations_name'), table_name='bot_configurations')
    op.drop_index(op.f('ix_bot_configurations_is_active'), table_name='bot_configurations')
    op.drop_index(op.f('ix_bot_configurations_id'), table_name='bot_configurations')
    op.drop_table('bot_configurations')
    # ### end Alembic commands ###
