"""Fix boolean fields in signals and patterns

Revision ID: b35efc842fde
Revises: 9260c9e2a970
Create Date: 2025-12-21 20:18:13.702514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35efc842fde'
down_revision: Union[str, None] = '9260c9e2a970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
