"""
Signal Model

This model stores trading signals generated by the bot.
Includes entry/exit prices, stop-loss, take-profit, and confidence scores.
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Index, JSON, Enum as SQLEnum
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum

from app.database import Base


class SignalType(enum.Enum):
    """Signal type enumeration"""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class SignalStatus(enum.Enum):
    """Signal status enumeration"""
    ACTIVE = "ACTIVE"
    EXECUTED = "EXECUTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class Signal(Base):
    """
    Signal Model
    
    Stores trading signals with entry/exit prices and risk management.
    Tracks signal performance and component contributions.
    """
    
    __tablename__ = "signals"
    
    # Primary Key
    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign Keys
    stock_id = Column(Integer, ForeignKey("stocks.id", ondelete="CASCADE"), nullable=False, index=True)
    bot_config_id = Column(Integer, ForeignKey("bot_configurations.id", ondelete="SET NULL"), nullable=True, index=True)
    
    # Signal Information
    signal_type = Column(SQLEnum(SignalType), nullable=False, index=True)
    status = Column(SQLEnum(SignalStatus), default=SignalStatus.ACTIVE, nullable=False, index=True)
    
    # Price Levels
    entry_price = Column(Float, nullable=False)
    stop_loss = Column(Float, nullable=False)
    take_profit_1 = Column(Float, nullable=True)
    take_profit_2 = Column(Float, nullable=True)
    take_profit_3 = Column(Float, nullable=True)
    
    # Risk Management
    risk_amount = Column(Float, nullable=True)  # Amount at risk
    reward_amount = Column(Float, nullable=True)  # Potential reward
    risk_reward_ratio = Column(Float, nullable=True)  # R:R ratio
    position_size = Column(Float, nullable=True)  # Recommended quantity
    
    # Confidence and Scoring
    confidence_score = Column(Float, nullable=False, index=True)  # Overall confidence (0-1)
    sector_score = Column(Float, nullable=True)  # Sector component score
    liquidity_score = Column(Float, nullable=True)  # Liquidity component score
    depth_score = Column(Float, nullable=True)  # Market depth score
    floorsheet_score = Column(Float, nullable=True)  # Floorsheet score
    technical_score = Column(Float, nullable=True)  # Technical indicators score
    
    # Component Flags
    sector_bullish = Column(Integer, default=False, nullable=False)
    in_demand_zone = Column(Integer, default=False, nullable=False)
    has_volume_spike = Column(Integer, default=False, nullable=False)
    has_breakout = Column(Integer, default=False, nullable=False)
    has_bid_wall = Column(Integer, default=False, nullable=False)
    has_accumulation = Column(Integer, default=False, nullable=False)
    
    # Technical Indicators (at signal generation)
    rsi = Column(Float, nullable=True)
    macd = Column(Float, nullable=True)
    ema_9 = Column(Float, nullable=True)
    ema_21 = Column(Float, nullable=True)
    
    # Pattern Information
    detected_patterns = Column(JSON, nullable=True)  # List of detected patterns
    
    # Signal Metadata
    signal_reason = Column(String(500), nullable=True)  # Human-readable reason
    component_details = Column(JSON, nullable=True)  # Detailed component analysis
    
    # Execution Tracking
    executed_at = Column(DateTime(timezone=True), nullable=True)
    executed_price = Column(Float, nullable=True)
    exit_price = Column(Float, nullable=True)
    exit_at = Column(DateTime(timezone=True), nullable=True)
    profit_loss = Column(Float, nullable=True)
    profit_loss_percent = Column(Float, nullable=True)
    
    # Validity
    valid_until = Column(DateTime(timezone=True), nullable=True)  # Signal expiry
    
    # Timestamps
    generated_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    stock = relationship("Stock", back_populates="signals")
    bot_config = relationship("BotConfiguration")
    
    # Indexes for performance
    __table_args__ = (
        Index('idx_signal_stock_id', 'stock_id'),
        Index('idx_signal_type', 'signal_type'),
        Index('idx_signal_status', 'status'),
        Index('idx_signal_confidence', 'confidence_score'),
        Index('idx_signal_generated', 'generated_at'),
        Index('idx_signal_stock_status', 'stock_id', 'status'),
        Index('idx_signal_active', 'status', 'valid_until'),
    )
    
    def __repr__(self):
        return f"<Signal(id={self.id}, stock_id={self.stock_id}, type={self.signal_type}, confidence={self.confidence_score})>"
    
    def to_dict(self, include_stock=False):
        """Convert model to dictionary"""
        data = {
            "id": self.id,
            "stock_id": self.stock_id,
            "bot_config_id": self.bot_config_id,
            "signal_type": self.signal_type.value if self.signal_type else None,
            "status": self.status.value if self.status else None,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit_1": self.take_profit_1,
            "take_profit_2": self.take_profit_2,
            "take_profit_3": self.take_profit_3,
            "risk_amount": self.risk_amount,
            "reward_amount": self.reward_amount,
            "risk_reward_ratio": self.risk_reward_ratio,
            "position_size": self.position_size,
            "confidence_score": self.confidence_score,
            "sector_score": self.sector_score,
            "liquidity_score": self.liquidity_score,
            "depth_score": self.depth_score,
            "floorsheet_score": self.floorsheet_score,
            "technical_score": self.technical_score,
            "sector_bullish": self.sector_bullish,
            "in_demand_zone": self.in_demand_zone,
            "has_volume_spike": self.has_volume_spike,
            "has_breakout": self.has_breakout,
            "has_bid_wall": self.has_bid_wall,
            "has_accumulation": self.has_accumulation,
            "rsi": self.rsi,
            "macd": self.macd,
            "ema_9": self.ema_9,
            "ema_21": self.ema_21,
            "detected_patterns": self.detected_patterns,
            "signal_reason": self.signal_reason,
            "component_details": self.component_details,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "executed_price": self.executed_price,
            "exit_price": self.exit_price,
            "exit_at": self.exit_at.isoformat() if self.exit_at else None,
            "profit_loss": self.profit_loss,
            "profit_loss_percent": self.profit_loss_percent,
            "valid_until": self.valid_until.isoformat() if self.valid_until else None,
            "generated_at": self.generated_at.isoformat() if self.generated_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None
        }
        
        if include_stock and self.stock:
            data["stock"] = {
                "symbol": self.stock.symbol,
                "name": self.stock.name,
                "ltp": self.stock.ltp
            }
        
        return data
